on: push
name: Test
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform:iOS Simulator, id:C7AC1720-A2D0-44A9-8DAC-35648E534423, OS:13.1, name:iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          pod install
          xcodebuild clean test -workspace "Binh Minh Collab.xcworkspace" -scheme "Binh Minh CollabTests" -destination "${destination}"
          bash <(curl -s https://codecov.io/bash)
        env: 
         destination: ${{ matrix.destination }}